### ISSUE TITLE
Alarm application not running

### ISSUE THREAD

**Issue by DavidEkemini** [HassanAlthaf/AlarmApplication#1]
Anytime i try to run the app it shows a  "Cannot find symbol" error on line 54 and line 62 of the Mainview.java class. 
so the app doesnt run at all.

**Comment by HassanAlthaf** [comment]
Sorry for the late reply. Could you please send me the error log completely?

**Comment by HassanAlthaf** [comment]
Ok, here's your solution: https://stackoverflow.com/questions/29525483/some-javafx-imports-cannot-be-resolved-in-eclipse
